server:
  port: 8043

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: otp
          uri: lb://OTP-SERVICE
          predicates:
            - Path=/otp/**

        - id: identity
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: email
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**

        - id: user-profile
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - Path=/api/user-profiles/**

        - id: medicine
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - Path=/medicine/**

        - id: cart
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        # âœ… Route for Address CRUD
        - id: address
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - Path=/address/**
